### ISSUE TITLE
unexpected end of data

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/cluster_tools#85]
I've had this exception running a long-running job on gaba.

The job seems to have completed successfully (`/tmpscratch/georgwie/artifacts/default/compute_segment_types/segment_types_sorted_probabilities__45f3b33b5c/cfut/slurmpy.stdout.15280248.log`). It seems like this is a problem with streaming the log. Not sure what could be the problem or if this happens often.

```
Traceback (most recent call last):
  File "/u/georgwie/conda-envs/segm-3.6_1/bin/vx", line 11, in <module>
    load_entry_point('voxelytics', 'console_scripts', 'vx')()
  File "/u/georgwie/voxelytics1/voxelytics/__main__.py", line 311, in main
    workflow.run(task_selection, strategy_for_task=strategy_for_task)
  File "/u/georgwie/voxelytics1/voxelytics/commons/workflow/workflow.py", line 255, in run
    execute()
  File "/u/georgwie/voxelytics1/voxelytics/commons/workflow/workflow.py", line 230, in execute
    task.execute()
  File "/u/georgwie/voxelytics1/voxelytics/connect/abstract_tasks/distributable_task.py", line 191, in execute
    executor.forward_log(fut)
  File "/u/georgwie/conda-envs/segm-3.6_1/lib/python3.6/site-packages/cluster_tools/schedulers/cluster_executor.py", line 353, in forward_log
    tailer.follow(2)
  File "/u/georgwie/conda-envs/segm-3.6_1/lib/python3.6/site-packages/cluster_tools/tailf.py", line 33, in follow
    line = file_.readline()
  File "/u/georgwie/conda-envs/segm-3.6_1/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 0: unexpected end of data
```

**Comment by daniel-wer** [comment]
Just to add, this happens regularly when executing the voxelytics `ComputeSegmentTypes` task leading to the whole workflow execution crashing.
This is another log that led to the same error (same stack trace): `/conndata/georgwie/artifacts/default/compute_segment_types/segment_types__b33db9d27b-v1/cfut/slurmpy.22182700.log.stdout`

It looks like the progress bar output gets interrupted by another log message, maybe leading to unicode multi-byte characters being split up which leads to the decoding error (just a guess). I would suggest to use pythons `error="replace"` parameter in the `open` call of the file, see here: https://stackoverflow.com/a/41652865

Let's get this fixed :)

**Comment by philippotto** [comment]
thanks for investigating this bug, @daniel-wer! your explanation and proposed solution sound very good. I opened #100 (:tada:) and hope that this simply does the trick, as I couldn't test it. However, the odds should be in our favor :)
